# Generated by Django 6.1 on 2026-08-13 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incident', '0002_analyseia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('resolu', 'Résolu')], default='en_cours', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='interventions/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to=settings.AUTH_USER_MODEL)),
                ('signalement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='incident.incident')),
            ],
        ),
    ]
