# Generated by Django 6.1 on 2026-08-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('resolu', 'Résolu'), ('annulee', 'Annulée')], default='en_cours', max_length=20),
        ),
    ]
