# Generated by Django 6.1 on 2026-08-12 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('en_cours', 'En Cours'), ('resolu', 'Résolu')], default='en_attente', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('messageVocal', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateModification', models.DateTimeField(auto_now=True)),
                ('priorite', models.CharField(blank=True, max_length=20, null=True)),
                ('urlImage', models.ImageField(upload_to='images/')),
                ('citoyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
