# Generated by Django 6.1 on 2026-08-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(max_length=64)),
                ('score_confiance', models.FloatField()),
                ('niveau_urgence', models.CharField(max_length=20)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incident')),
            ],
        ),
    ]
