# Generated by Django 6.1 on 2026-08-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_analyseia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
