# Generated by Django 6.1 on 2026-08-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='telophone',
            new_name='telephone',
        ),
    ]
