# Generated by Django 6.1 on 2026-08-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
