# Generated by Django 6.1 on 2026-08-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='tentative',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
