# Generated by Django 6.1 on 2026-08-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_otp_tentative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
